# Generated by Django 6.0.3 on 2026-04-01 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
                ('signal', models.CharField(choices=[('BUY', 'Acheter'), ('SELL', 'Vendre'), ('HOLD', 'Attendre')], max_length=4, verbose_name='Signal IA')),
                ('confidence', models.FloatField(verbose_name='Confiance (%)')),
                ('predicted_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Prix prédit')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Prix réel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Prédiction IA',
                'verbose_name_plural': 'Prédictions IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Prix du marché',
                'verbose_name_plural': 'Prix du marché',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bot actif')),
                ('min_confidence', models.FloatField(default=0.75, verbose_name='Confiance minimum')),
                ('max_trade_amount', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Montant max / trade')),
                ('stop_loss_pct', models.FloatField(default=5.0, verbose_name='Stop-loss (%)')),
                ('paper_trading', models.BooleanField(default=False, verbose_name='Paper trading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Configuration Bot',
                'verbose_name_plural': 'Configurations Bot',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbole')),
                ('action', models.CharField(choices=[('BUY', 'Acheter'), ('SELL', 'Vendre')], max_length=4, verbose_name='Action')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Prix')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('confidence', models.FloatField(verbose_name='Confiance IA (%)')),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit / Perte')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Exécuté le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-executed_at'],
            },
        ),
    ]
