# Generated by Django 5.2.13 on 2026-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_enabled', models.BooleanField(default=True, verbose_name='Trading activé')),
                ('max_trade_amount', models.FloatField(default=1000.0, verbose_name='Montant max / trade')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=10, verbose_name='Niveau de risque')),
                ('auto_trade', models.BooleanField(default=False, verbose_name='Trading automatique')),
                ('min_confidence', models.FloatField(default=0.75, verbose_name='Confiance minimum IA')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètres Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
    ]
